TOKEN = "" #PUT DISCORD TOKE HERE
PREFIX = "!" #CHOOSE BOT PREFIX HERE


# ---- CHAT BOT API ----#
CHAT_API_KEY = "" #PUT YOUR BRAINSHOP.IO BOT TOKEN HERE OR SIGN UP IF YOU DONT HAVE ONE
CHAT_API_ID = "" #PUT CHATBOT ID HERE
